#Minecraft server properties
#Mon Jun 22 15:00:52 CEST 2026
accepts-transfers=false
allow-flight=true
broadcast-console-to-ops=false
broadcast-rcon-to-ops=false
bug-report-link=
debug=false
difficulty=easy
enable-code-of-conduct=false
enable-command-block=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=false
enforce-whitelist=false
entity-broadcast-range-percentage=75
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=event_world
level-seed=macecup-crystal-rift-1250x1250
level-type=minecraft\:normal
log-ips=true
management-server-allowed-origins=
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=NLuhyZyTdGY5oJ8NUbeN140KdMaofsalQhDFP9rE
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
max-chained-neighbor-updates=1000000
max-players=100
max-tick-time=60000
max-world-size=29999984
motd=§8§lMaceCup §7| §b§lMace PvP\n§7IP\: §bmacecup.xyz §8» §fMacePvP
network-compression-threshold=-1
online-mode=false
op-permission-level=4
pause-when-empty-seconds=-1
player-idle-timeout=0
prevent-proxy-connections=false
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=
resource-pack-id=bafd3464-423c-4e03-930b-0e5ba2d83594
resource-pack-prompt={"text"\:"Our server uses a custom resource pack\!", "color"\:"gold"}
resource-pack-sha1=a56922eb1a1a501342138d03e6654bf66800bd50
server-ip=127.0.0.1
server-port=25565
simulation-distance=6
spawn-protection=0
status-heartbeat-interval=0
sync-chunk-writes=false
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=10
white-list=false
